//
//  FAPaintCode.h
//  FlavorsAcademy
//
//  Created by Alminty on 1/13/16.
//  Copyright (c) 2016 Alminty. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface FAPaintCode : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* backBtnTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* menuBtnTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* downArrowBlackTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* upArrowBlackTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* playBtnEmptyTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* playBtnFilledTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* closeBtnTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* starEmptyTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* starFilledTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* searchBtnTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* locationBtnTargets;

// Drawing Methods
+ (void)drawSearchBtn;
+ (void)drawLocationBtn;
+ (void)drawEightsideLoading;

// Generated Images
+ (UIImage*)imageOfBackBtn;
+ (UIImage*)imageOfMenuBtn;
+ (UIImage*)imageOfDownArrowBlack;
+ (UIImage*)imageOfUpArrowBlack;
+ (UIImage*)imageOfPlayBtnEmpty;
+ (UIImage*)imageOfPlayBtnFilled;
+ (UIImage*)imageOfCloseBtn;
+ (UIImage*)imageOfStarEmpty;
+ (UIImage*)imageOfStarFilled;
+ (UIImage*)imageOfSearchBtn;
+ (UIImage*)imageOfLocationBtn;

@end



@interface UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end
